# Generated by Django 4.2.5 on 2023-09-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_compra_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
