# Generated by Django 4.2.5 on 2023-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0003_remove_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
