# Generated by Django 4.2.5 on 2023-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0004_alter_compra_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(blank=True, to='AppTienda.producto'),
        ),
    ]
